[project]
name = "parakeet-asr-fastapi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9.13"
dependencies = [
    "fastapi>=0.115.12",
    "omegaconf>=2.3.0",
    "pydantic>=2.11.4",
    "uvicorn>=0.34.2",
]
